---
title: CredentialsError
description: API reference for qiskit.providers.ibmq.credentials.CredentialsError
in_page_toc_min_heading_level: 1
python_api_type: exception
python_api_name: qiskit.providers.ibmq.credentials.CredentialsError
---

# CredentialsError

<span id="qiskit.providers.ibmq.credentials.CredentialsError" />

`CredentialsError(*message)`

Base class for errors raised during credential management.

Set the error message.

### with\_traceback

<span id="qiskit.providers.ibmq.credentials.CredentialsError.with_traceback" />

`with_traceback()`

Exception.with\_traceback(tb) â€“ set self.\_\_traceback\_\_ to tb and return self.

