---
title: IBMQAccountCredentialsInvalidUrl
description: API reference for qiskit.providers.ibmq.IBMQAccountCredentialsInvalidUrl
in_page_toc_min_heading_level: 1
python_api_type: exception
python_api_name: qiskit.providers.ibmq.IBMQAccountCredentialsInvalidUrl
---

# IBMQAccountCredentialsInvalidUrl

<span id="qiskit.providers.ibmq.IBMQAccountCredentialsInvalidUrl" />

`IBMQAccountCredentialsInvalidUrl(*message)`

Errors raised when an IBM Quantum Experience URL is invalid.

Set the error message.

### with\_traceback

<span id="qiskit.providers.ibmq.IBMQAccountCredentialsInvalidUrl.with_traceback" />

`with_traceback()`

Exception.with\_traceback(tb) â€“ set self.\_\_traceback\_\_ to tb and return self.

