---
title: InvalidCredentialsFormatError
description: API reference for qiskit.providers.ibmq.credentials.InvalidCredentialsFormatError
in_page_toc_min_heading_level: 1
python_api_type: exception
python_api_name: qiskit.providers.ibmq.credentials.InvalidCredentialsFormatError
---

# InvalidCredentialsFormatError

<span id="qiskit.providers.ibmq.credentials.InvalidCredentialsFormatError" />

`InvalidCredentialsFormatError(*message)`

Errors raised when the credentials are in an invalid format.

Set the error message.

### with\_traceback

<span id="qiskit.providers.ibmq.credentials.InvalidCredentialsFormatError.with_traceback" />

`with_traceback()`

Exception.with\_traceback(tb) â€“ set self.\_\_traceback\_\_ to tb and return self.

